"""Export a TFLite model as a C byte array for firmware embedding.

Equivalent to ``xxd -i model.tflite``, but produced directly from Python so
the exact bytes trained and evaluated in this session are the ones that end
up in ``firmware/esp32s3/main/model_data.cc`` — no separate manual export
step to drift out of sync.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import numpy.typing as npt

_BYTES_PER_LINE = 12


def tflite_to_c_source(tflite_model: bytes, var_name: str = "g_vibration_model") -> tuple[str, str]:
    """Render a TFLite model as C header + source file contents.

    Args:
        tflite_model: Raw ``.tflite`` flatbuffer bytes.
        var_name: C identifier for the model byte array.

    Returns:
        ``(header_contents, source_contents)``.
    """
    guard = f"TINYML_VIBRATION_{var_name.upper()}_H_"
    lines = []
    for i in range(0, len(tflite_model), _BYTES_PER_LINE):
        chunk = tflite_model[i : i + _BYTES_PER_LINE]
        lines.append(", ".join(f"0x{b:02x}" for b in chunk))
    body = ",\n".join(lines)

    header = (
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        "// Auto-generated by tinyml_vibration.models.export_c. Do not edit by hand;\n"
        "// regenerate with `python -m tinyml_vibration.pipeline`.\n\n"
        f"extern const unsigned char {var_name}[];\n"
        f"extern const unsigned int {var_name}_len;\n\n"
        f"#endif  // {guard}\n"
    )
    source = (
        f'#include "{var_name}.h"\n\n'
        "// Auto-generated by tinyml_vibration.models.export_c. Do not edit by hand;\n"
        "// regenerate with `python -m tinyml_vibration.pipeline`.\n\n"
        f"alignas(16) const unsigned char {var_name}[] = {{\n{body}\n}};\n"
        f"const unsigned int {var_name}_len = {len(tflite_model)};\n"
    )
    return header, source


def write_c_source_files(
    tflite_model: bytes, output_dir: str | Path, var_name: str = "g_vibration_model"
) -> tuple[Path, Path]:
    """Write ``<var_name>.h`` and ``<var_name>.cc`` into ``output_dir``."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    header, source = tflite_to_c_source(tflite_model, var_name)
    header_path = output_dir / f"{var_name}.h"
    source_path = output_dir / f"{var_name}.cc"
    header_path.write_text(header)
    source_path.write_text(source)
    return header_path, source_path


def write_test_vectors(
    windows_int8: npt.NDArray[np.int8],
    labels: list[str],
    output_dir: str | Path,
    var_name: str = "g_test_vectors",
) -> tuple[Path, Path]:
    """Export a handful of pre-quantized int8 windows for an on-device self-test.

    Lets the firmware run real inferences at boot (one per known-label
    sample) without needing a physical sensor attached yet, so the model
    integration itself can be validated on hardware independently of the
    sensor driver.

    Args:
        windows_int8: Array of shape ``(n, window_length)``, already
            quantized to the model's int8 input representation.
        labels: Ground-truth class name for each row of ``windows_int8``.
        output_dir: Directory to write ``<var_name>.h`` / ``.cc`` into.
        var_name: C identifier prefix for the generated arrays.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    n, window_length = windows_int8.shape
    guard = f"TINYML_VIBRATION_{var_name.upper()}_H_"

    header = (
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        "// Auto-generated by tinyml_vibration.models.export_c. Do not edit by hand;\n"
        "// regenerate with `python -m tinyml_vibration.pipeline`.\n\n"
        f"#define {var_name.upper()}_COUNT {n}\n"
        f"#define {var_name.upper()}_WINDOW_LENGTH {window_length}\n\n"
        f"extern const signed char {var_name}_data[{var_name.upper()}_COUNT]"
        f"[{var_name.upper()}_WINDOW_LENGTH];\n"
        f"extern const char *const {var_name}_labels[{var_name.upper()}_COUNT];\n\n"
        f"#endif  // {guard}\n"
    )

    rows = []
    for row in windows_int8:
        lines = []
        for i in range(0, window_length, _BYTES_PER_LINE):
            chunk = row[i : i + _BYTES_PER_LINE]
            lines.append(", ".join(str(int(v)) for v in chunk))
        rows.append("  {\n    " + ",\n    ".join(lines) + "\n  }")
    data_body = ",\n".join(rows)
    labels_body = ",\n".join(f'  "{label}"' for label in labels)

    source = (
        f'#include "{var_name}.h"\n\n'
        "// Auto-generated by tinyml_vibration.models.export_c. Do not edit by hand;\n"
        "// regenerate with `python -m tinyml_vibration.pipeline`.\n\n"
        f"const signed char {var_name}_data[{var_name.upper()}_COUNT]"
        f"[{var_name.upper()}_WINDOW_LENGTH] = {{\n{data_body}\n}};\n\n"
        f"const char *const {var_name}_labels[{var_name.upper()}_COUNT] = {{\n{labels_body}\n}};\n"
    )

    header_path = output_dir / f"{var_name}.h"
    source_path = output_dir / f"{var_name}.cc"
    header_path.write_text(header)
    source_path.write_text(source)
    return header_path, source_path
