#ifndef TINYML_VIBRATION_G_TEST_VECTORS_H_
#define TINYML_VIBRATION_G_TEST_VECTORS_H_

// Auto-generated by tinyml_vibration.models.export_c. Do not edit by hand;
// regenerate with `python -m tinyml_vibration.pipeline`.

#define G_TEST_VECTORS_COUNT 4
#define G_TEST_VECTORS_WINDOW_LENGTH 2048

extern const signed char g_test_vectors_data[G_TEST_VECTORS_COUNT][G_TEST_VECTORS_WINDOW_LENGTH];
extern const char *const g_test_vectors_labels[G_TEST_VECTORS_COUNT];

#endif  // TINYML_VIBRATION_G_TEST_VECTORS_H_
