#ifndef TINYML_VIBRATION_G_VIBRATION_MODEL_H_
#define TINYML_VIBRATION_G_VIBRATION_MODEL_H_

// Auto-generated by tinyml_vibration.models.export_c. Do not edit by hand;
// regenerate with `python -m tinyml_vibration.pipeline`.

extern const unsigned char g_vibration_model[];
extern const unsigned int g_vibration_model_len;

#endif  // TINYML_VIBRATION_G_VIBRATION_MODEL_H_
